export enum ProfileTypes {
    GET_PROFILE = 'GET_PROFILE',
    GET_PROFILE_PENDING = 'GET_PROFILE_PENDING',
    GET_PROFILE_FULFILLED = 'GET_PROFILE_FULFILLED',
    GET_PROFILE_REJECTED = 'GET_PROFILE_REJECTED',
  }